export const uiText = {
  nav: {
    sf10: 'SF10 (Student Permanent Record)',
    alumni: 'Alumni',
  },
  sf10: {
    title: 'SF10 (Student Permanent Record)',
    subtitle: 'Manage student SF10 records (mock/local data)',
    searchPlaceholder: 'Search by student name or ID…',
    actions: {
      view: 'View SF10',
      download: 'Download (mock PDF)',
      print: 'Print',
      addStudent: 'Add student',
      editSf10: 'Edit SF10',
      removeStudent: 'Remove',
      backToList: 'Back to students list',
    },
    table: {
      id: 'Student ID',
      name: 'Student Name',
      gradeLevel: 'Grade Level',
      section: 'Section',
      status: 'Status',
      sf10: 'SF10',
      controls: 'Controls',
      hasRecord: 'OK',
      noResults: 'No students matched your search.',
    },
    sf10View: {
      header: 'Student Permanent Record',
      profile: 'Learner Profile',
      schoolInfo: 'School Information',
      gradeRecords: 'Grade Records',
      remarks: 'Remarks',
      subject: 'Subject',
      final: 'Final',
      subjectRemarks: 'Remarks',
      generalAverage: 'General Average',
    },
    placeholders: {
      download: 'Mock download: PDF generation will be added in a later phase.',
      print: 'Printing…',
      add: 'UI only: Add student flow will be added later.',
      edit: 'UI only: SF10 editor will be added later.',
      remove: 'UI only: Remove action will be wired later.',
    },
  },
  alumni: {
    title: 'Alumni',
    subtitle: 'Browse alumni grouped by batch year (mock/local data)',
    searchPlaceholder: 'Search by name…',
    filterYearLabel: 'Batch year',
    allYears: 'All years',
    noResults: 'No alumni matched your filters.',
    fields: {
      programOrGrade: 'Program / Grade',
      notes: 'Notes',
      achievements: 'Achievements',
    },
  },
}
